version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: awsAthena
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - mysql_data:/var/lib/mysql

    minio:
        image: minio/minio
        container_name: minio
        restart: always
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data

volumes:
    mysql_data:
    minio_data:
